### ISSUE TITLE
how to use the gem?

### ISSUE THREAD

**Issue by cimenta** [apuruni/salesforce_http_client#1]
Hi

any chance you can help me to use your gem?

I want to use just simple .rb script to download a report.

I installed the gem successfully by gem install gem salesforce_http_client

But now I am not sure how to use it. Below code doesn't seem to work for me. 

It gives me this error

ruby getreport.rb
C:/Ruby193/lib/ruby/gems/1.9.1/gems/salesforce_http_client-0.1.3/lib/salesforce_
http_client/salesforce_http_access.rb:13:in `create_http_client': uninitialized
constant SalesforceHttpClient::SalesforceHttpAccess::HTTPClient (NameError)
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/salesforce_http_client-0.1.3/li
b/salesforce_http_client/salesforce_http_access.rb:6:in`download_from_salesforc
e'
        from C:/Ruby193/lib/ruby/gems/1.9.1/gems/salesforce_http_client-0.1.3/li
b/salesforce_http_client/client.rb:17:in `download_report'
        from getreport.rb:16:in`<main>'
# 

require  'salesforce_http_client'

SalesforceHttpClient.configure do |config|
  config.salesforce_login_id = 'my_login_id_or_email'
  config.salesforce_password = 'my_password'
end

salesforce_id = '000000000000ABC'
report_save_path = "tmp/#{salesforce_id}.csv"

sf_client = SalesforceHttpClient::Client.new
sf_client.download_report(salesforce_id, report_save_path)

**Comment by cimenta** [comment]
ok the solution was to add these two lines

require 'fileutils'
require 'httpclient'

**Comment by apuruni** [comment]
Added to README.md. 
Thank you very much.
