### ISSUE TITLE
ERROR -- : failed to download reports.

### ISSUE THREAD

**Issue by cimenta** [apuruni/salesforce_http_client#2]
Hi

I am getting this error.

E, [2015-04-17T22:15:44.084389 #10404] ERROR -- : failed to download reports.

Could you help me to debug it?

Thank you

R

**Comment by cimenta** [comment]
E, [2015-04-17T22:23:16.280253 #6004] ERROR -- : failed to download reports.

**Comment by apuruni** [comment]
You get "failed to download reports." error message because the http request to salesforce.com returns some error.
You must set the right saleforce ID for you report.

> First, you need find the salesforce ID for your report. For example: 
> http://na1.salesforce.com/000000000000ABC, where '000000000000ABC' is the salesforce ID.

here is the part of code.

https://github.com/apuruni/salesforce_http_client/blob/master/lib/salesforce_http_client/salesforce_http_access.rb

```
    def download_and_save_report(report_id, output_save_path)
      @logger.info "begin download reports"
      response = @http_client.get report_url(report_id)
      if response.status == 200
        save_report(response, output_save_path)
      else
        @logger.error "failed to download reports."
      end
    end
```

**Comment by cimenta** [comment]
Hi

I am not able to debug the code. You might help me?

The url to the report is https://na12.salesforce.com/00OU0000002JtVG

and my script contains salesforce_id = '00OU0000002JtVG'

When I log into SF and use above url I get the report I want. 

I double checked login credentials and all is good.

Any idea?

Thank you

R

**Comment by apuruni** [comment]
I think this is a salesforce region problem.
Setting config.salesforce_report_url_format property may be work.  
  config.salesforce_report_url_format = 'https://na12.salesforce.com/#{report_id}?export=1&enc=UTF-8&xf=csv'

Here is configuration sample.

```
      Configuration.configure do |config|
          config.salesforce_login_id = 'test_login_id'
          config.salesforce_password = 'test_password'
          config.salesforce_report_url_format = 'https://na12.salesforce.com/#{report_id}?export=1&enc=UTF-8&xf=csv'
        end
```

**Comment by cimenta** [comment]
beautiful. It worked nicely.

Maybe you can add this to the documentation.

Thank you so much.

R

**Comment by apuruni** [comment]
Thank you for your advice. I will update README soon.

**Comment by cimenta** [comment]
Thank you for your gem ;-)

**Comment by apuruni** [comment]
Added to README.md. 
Thank you very much.
