### ISSUE TITLE
save report to a variable?

### ISSUE THREAD

**Issue by cimenta** [apuruni/salesforce_http_client#3]
Hi

is there any way how I can save the report to a variable only? Not to a file on the disk?

Thank you

R

**Comment by apuruni** [comment]
Did you mean you need a String variable contains the report content?
You can try this code.

```
sf_client.download_report(salesforce_id, report_save_path)
report_content = File.open(report_save_path, "rb").read
```

**Comment by cimenta** [comment]
Yes, I meant that. It will work. Thank you. R

**Comment by apuruni** [comment]
I think saving to a file is more generic. Maybe it is not enough.
