### ISSUE TITLE
save url to the case

### ISSUE THREAD

**Issue by cimenta** [apuruni/salesforce_http_client#4]
Hi

could you also make it so url to the case is saved?

Thank you

R

**Comment by apuruni** [comment]
The default instance in this gem is ap.salesforce.com, a Asian Pacific region sub domain.
Your salesforce account is using na12.salesforce.com,  a North American region sub domain.

It seems that salesforce.com has many sub domains, and one can only use the right sub domain to access salesforce.com resources.
So the right sub domain must be set except  asian pacific region.

I can make it easier to set the sub domain parameter.

**Comment by cimenta** [comment]
What I meant is that from the report that I can save using your same I want to create a html table where the column case number would be clickable. If clicked it would open new tab with the case details.

For example for case #1447956 the url would be https://na12.salesforce.com/500U000000DuzRi 

Not sure if you can help here.

**Comment by apuruni** [comment]
Oh, Maybe this issue is out of the scope of this gem.

But I think you can try the way blow.
1. Set _case details_ Object ID as a output field of your report.
2. In your Html, use _case details_ Object ID to make the link.

**Comment by cimenta** [comment]
Perfect solution. Works nicely.

I cannot find in the code how your gem logs into SF. Could you help me?

Thank you

**Comment by apuruni** [comment]
It's a trick by simulating login actions as if you are login with a normal browser. :)

The source code is in code blow. 
https://github.com/apuruni/salesforce_http_client/blob/master/lib/salesforce_http_client/salesforce_http_access.rb
Method: salesforce_login

**Comment by cimenta** [comment]
hmm, before I found your gem I did research on using mechanize. I found some posts saying that it won't work because SF is using javascript. Then I found your gem and it looks that I can do what I wanted.

Just in case I need to use mechanize it seems to me that it would work with SF. What do you think.

**Comment by apuruni** [comment]
I think you can use it until SF make changes in login process.
I am using this gem in my business jobs, as cron tasks. 
It works well by now.

**Comment by cimenta** [comment]
cool. Thank you so much for your help

**Comment by apuruni** [comment]
:)
